# Generated by Django 5.0.6 on 2024-06-26 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Create ip', 'create new internal passport'), ('Create fp', 'create new foreign passport'), ('Create v', 'create new visa'), ('Restore ip - loss', 'restore an internal passport due to loss'), ('Restore fp - loss', 'restore an foreign passport due to loss'), ('Restore ip - expiry', 'restore an internal passport due to expiration'), ('Restore fp - expiry', 'restore an foreign passport due to expiration'), ('Change data', 'change passport data')], max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'in progress'), (1, 'completed')], default=0)),
                ('user_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
