# Generated by Django 5.0.6 on 2024-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(choices=[('Create ip', 'create new internal passport'), ('Create fp', 'create new foreign passport'), ('Create v', 'create new visa'), ('Restore ip - loss', 'restore an internal passport due to loss'), ('Restore fp - loss', 'restore an foreign passport due to loss'), ('Restore ip - expiry', 'restore an internal passport due to expiration'), ('Restore fp - expiry', 'restore an foreign passport due to expiration'), ('Change data', 'change passport data'), ('Restore address', 'restore a registration address')], max_length=50),
        ),
    ]
