# Generated by Django 5.0.6 on 2024-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='district',
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
