# Generated by Django 5.0.6 on 2024-09-02 16:09

import validation.validate_expiry_date
import validation.validate_issue_date
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0002_alter_foreignpassport_authority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visa',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visa',
            name='date_of_expiry',
            field=models.DateField(validators=[validation.validate_expiry_date.validate_expiry_date]),
        ),
        migrations.AlterField(
            model_name='visa',
            name='date_of_issue',
            field=models.DateField(validators=[validation.validate_issue_date.validate_issue_date]),
        ),
        migrations.AlterField(
            model_name='visa',
            name='entry_amount',
            field=models.CharField(choices=[('1', 'Single Entry'), ('2', 'Double Entry'), ('MULT', 'Multiple Entry')], max_length=4),
        ),
        migrations.AlterField(
            model_name='visa',
            name='photo',
            field=models.ImageField(upload_to='photos/visas/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='visa',
            name='type',
            field=models.CharField(choices=[('Employment', 'Employment Type'), ('Business', 'Business Type'), ('Tourist', 'Tourist Type'), ('Student', 'Student Type'), ('Transit', 'Transit Type')], max_length=50),
        ),
    ]
