# Generated by Django 5.0.6 on 2024-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0002_remove_address_district_alter_address_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visa',
            name='place_of_issue',
            field=models.CharField(max_length=50),
        ),
    ]
