# Generated by Django 5.0.6 on 2024-06-25 13:15

import django.db.models.deletion
import validation.validate_birth_date
import validation.validate_email
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(editable=False, max_length=254, unique=True, validators=[validation.validate_email.validate_email])),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('patronymic', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('date_of_birth', models.DateField(validators=[validation.validate_birth_date.validate_birth_date])),
                ('place_of_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='passports.address')),
                ('foreign_passport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='passports.foreignpassport')),
                ('passport', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='passports.passport')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
