name: Django Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories for logs
        run: mkdir -p logs

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run Celery worker
        run: |
          celery -A <your_project_name> worker --loglevel=info &
        env:
          CELERY_BROKER_URL: redis://localhost:6379/0

      - name: Run tests
        run: |
          pytest --maxfail=10 --disable-warnings
        env:
          CELERY_BROKER_URL: redis://localhost:6379/0
